import { Inter } from "next/font/google";
import "./globals.css";
import MagicProvider from "./context/MagicProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Prisoner's dilemma",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <MagicProvider>
        <body className={inter.className}>{children}</body>
      </MagicProvider>
    </html>
  );
}
